server:
    port: 13103
    contextPath: /security-demo
    servlet-path: /
logging:
    level:
        com.springsecurity.demo: DEBUG
        org.springframework.security.web.FilterChainProxy: DEBUG
        org.springframework.web.servlet.DispatcherServlet: DEBUG
        org.springframework.security.access.intercept.AbstractSecurityInterceptor: DEBUG
        org.springframework.security.web.access.intercept.FilterSecurityInterceptor: DEBUG
        org.springframework.security.access.AbstractAccessDecisionManager: debug
        org.springframework.security.access.AccessDecisionManager: debug
        org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor: debug
        org.springframework.security.access.intercept.aspectj.AspectJSecurityInterceptor: debug
spring:
    profiles:
#        active: showAllFilterDemo
#        active: n3_preAuth_selfAuth_logout
        active: n3_preAuth_selfAuth_logout_DB
#        active: n3_preAuth_selfAuth_logout_share_session
    datasource:
#        driver-class-name: org.h2.Driver
#        url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
#        username: sa
#        password: sa
        url: jdbc:mysql://127.0.0.1:3306/spring_security_demo?characterEncoding=UTF-8&useSSL=false&createDatabaseIfNotExist=true
        username: root
        password:
        driver: com.mysql.jdbc.Driver
        test-on-borrow: true
        test-while-idle: true
        validation-query: SELECT 1;
        tomcat:
            test-on-borrow: true
            validation-query: SELECT 1
            max-active: 5
            max-idle: 20
            min-idle: 15
            initial-size: 1
    jpa:
        hibernate:
            ddl-auto: none
            dialect: org.hibernate.dialect.H2Dialect
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            format_sql: true


liquibase:
    changeLog: "classpath:db-changelog/master.xml"