server:
    port: 13103
    contextPath: /security-demo
    servlet-path: /
logging:
    level:
        com.springsecurity.demo: DEBUG
        org.springframework.security.web.FilterChainProxy: DEBUG
        org.springframework.web.servlet.DispatcherServlet: DEBUG
        org.springframework.security.access.intercept.AbstractSecurityInterceptor: DEBUG
        org.springframework.security.web.access.intercept.FilterSecurityInterceptor: DEBUG
        org.springframework.security.access.AbstractAccessDecisionManager: debug
        org.springframework.security.access.AccessDecisionManager: debug
        org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor: debug
        org.springframework.security.access.intercept.aspectj.AspectJSecurityInterceptor: debug
n
#        active: n3_preAuth_selfAuth_logout_DB, h2
#        active: n3_preAuth_selfAuth_logout_share_session, h2


liquibase:
    changeLog: "classpath:db-changelog/master.xml"